DIRECTORY:
  dataset: /Users/inho/Desktop/DATA/01_splitdataset
  sample: /Users/inho/Desktop/DATA/sample_submission.csv
  phase: test

TRAIN:
  train_serial: '20220623_043115'

PREDICT:
  seed: 42
  gpu: 0
