DIRECTORY:
  dataset: /content/drive/MyDrive/DATA/01_splitdataset
  sample: /content/drive/MyDrive/DATA/sample_submission.csv
  phase: test

TRAIN:
  train_serial: '20220713_214128'

PREDICT:
  seed: 42
  gpu: 0
