DIRECTORY:
  dataset: /content/drive/MyDrive/DATA/01_splitdataset

TRAINER :
  model: convnext
  optimizer: SGD
  learning_rate: 5.0e-4
  weight_decay: 0.005
  loss: crossentropy
  metric:
    - accuracy
    - f1macro
  n_epochs: 30
  early_stopping_target: val_accuracy
  early_stopping_patience: 10
  early_stopping_mode: max
  amp: False
  gpu: 0
  seed: 42
  
MODEL:
  Linear:
    n_inputs:  784
    n_outputs: 5
  effnet:
    n_outputs: 5
  convnext:
    n_outputs: 5

DATALOADER:
  batch_size: 4
  num_workers: 2
  shuffle: True
  pin_memory: True
  drop_last: False

LOGGER:
  wandb: False
  logging_interval: 100
  plot:
    - loss
    - accuracy
    - f1macro
    - elapsed_time

